<?php /* Smarty version 2.6.11, created on 2010-10-12 08:55:33
         compiled from atak/index.tpl */ ?>
<script type="text/javascript" src="<?php echo $this->_tpl_vars['javascript_dir']; ?>
attack.js"></script>
<?php echo '';  if ($this->_tpl_vars['error'] != ''):  echo '<div style="color:red">';  echo $this->_tpl_vars['error'];  echo '</div>';  endif;  echo '';  if ($this->_tpl_vars['info'] != ''):  echo '<div style="color:#dcb373; font-weight:bold">';  echo $this->_tpl_vars['info'];  echo '</div>';  endif;  echo '<form  method="post" name="attack_form"><table width="80%" cellspacing="1" cellpadding="3" style="color: #B0A392; font-size: 11px;"><tr><td colspan="2"><font color=pink>Je¶li co¶ nie dzia³a jak trzeba od¶wie¿ stronê przez Ctrl+F5</font></td></tr><tr><td colspan="2">Ilo¶æ tur potrzebnych do osi±gniêcia pozycji wroga wynosi: ';  echo $this->_tpl_vars['tour_to_attack'];  echo '</td></tr><tr><td>Cel ataku:</td> <td><input  class="textFieldType1" name="attack[kogo]" type="text" value="';  echo $this->_tpl_vars['attack']['kogo'];  echo '"></td></tr><tr><td>Rodzja ataku:</td><td><select  class="textFieldType1" name="attack[type]" onChange="attack_type_change()"><option value="1" ';  if ($this->_tpl_vars['attack']['type'] == 1):  echo 'selected';  endif;  echo '>Gospodarka</option><option value="2" ';  if ($this->_tpl_vars['attack']['type'] == 2):  echo 'selected';  endif;  echo '>Ziemia</option><option value="3" ';  if ($this->_tpl_vars['attack']['type'] == 3):  echo 'selected';  endif;  echo '>Szpiegowanie</option><option value="4" ';  if ($this->_tpl_vars['attack']['type'] == 4):  echo 'selected';  endif;  echo '>Podpalanie</option><option value="5" ';  if ($this->_tpl_vars['attack']['type'] == 5):  echo 'selected';  endif;  echo '>Budynek koñcowy</option><option value="6" ';  if ($this->_tpl_vars['attack']['type'] == 6):  echo 'selected';  endif;  echo '>Koalicyjny</option><option value="7" ';  if ($this->_tpl_vars['attack']['type'] == 7):  echo 'selected';  endif;  echo '>Kradzie¿</option><option value="8" ';  if ($this->_tpl_vars['attack']['type'] == 8):  echo 'selected';  endif;  echo '>Skrytobójstwo</option><option value="9" ';  if ($this->_tpl_vars['attack']['type'] == 9):  echo 'selected';  endif;  echo '>Oblê¿enie</option><option value="10" ';  if ($this->_tpl_vars['attack']['type'] == 10):  echo 'selected';  endif;  echo '>Propaganda</option></select></td></tr><tr><td>³ucznicy:';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "help/template.quickhelp.tpl", 'smarty_include_vars' => array('helpfile' => 'archer')));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td> <td><input  class="textFieldType1" name="attack[lucznicy]" type="text" value="';  echo $this->_tpl_vars['attack']['lucznicy'];  echo '" onkeyup="koszt(';  echo $this->_tpl_vars['kingdomInfo']['zloto'];  echo ',';  echo $this->_tpl_vars['kingdomInfo']['jedzenie'];  echo ',';  echo $this->_tpl_vars['tour_to_attack'];  echo ')"></td></tr><tr><td>piechota:';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "help/template.quickhelp.tpl", 'smarty_include_vars' => array('helpfile' => 'infantry')));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td> <td><input class="textFieldType1"  name="attack[piechota]" type="text" value="';  echo $this->_tpl_vars['attack']['piechota'];  echo '" onkeyup="koszt(';  echo $this->_tpl_vars['kingdomInfo']['zloto'];  echo ',';  echo $this->_tpl_vars['kingdomInfo']['jedzenie'];  echo ',';  echo $this->_tpl_vars['tour_to_attack'];  echo ')"></td></tr><tr><td>husaria:';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "help/template.quickhelp.tpl", 'smarty_include_vars' => array('helpfile' => 'cavalry')));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td> <td><input class="textFieldType1" name="attack[husaria]" type="text" value="';  echo $this->_tpl_vars['attack']['husaria'];  echo '" onkeyup="koszt(';  echo $this->_tpl_vars['kingdomInfo']['zloto'];  echo ',';  echo $this->_tpl_vars['kingdomInfo']['jedzenie'];  echo ',';  echo $this->_tpl_vars['tour_to_attack'];  echo ')"></td></tr><tr><td>szpiedzy:</td> <td><input class="textFieldType1" name="attack[spy]" type="text" value="';  echo $this->_tpl_vars['attack']['spy'];  echo '" onkeyup="koszt(';  echo $this->_tpl_vars['kingdomInfo']['zloto'];  echo ',';  echo $this->_tpl_vars['kingdomInfo']['jedzenie'];  echo ',';  echo $this->_tpl_vars['tour_to_attack'];  echo ')"></td></tr><tr><td>Koszt z³ota:</td><td><div id="koszt_id" style="font-weight: bold; display: inline">0</div>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "help/template.quickhelp.tpl", 'smarty_include_vars' => array('helpfile' => 'attack_cost')));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td></tr><tr><td>Koszt jedzenia:</td><td><div id="koszt_jedzenia_id" style="font-weight: bold; display: inline">0</div>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "help/template.quickhelp.tpl", 'smarty_include_vars' => array('helpfile' => 'attack_cost')));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</td></tr><tr><td colspan="2" align="center"><input class="button" type="submit" value="Wyslij"></td></tr></table></form><script type="text/javascript" language="JavaScript">attack_type_change();koszt(';  echo $this->_tpl_vars['kingdomInfo']['zloto'];  echo ',';  echo $this->_tpl_vars['kingdomInfo']['jedzenie'];  echo ',';  echo $this->_tpl_vars['tour_to_attack'];  echo ');</script>'; ?>
