<?php /* Smarty version 2.6.11, created on 2010-07-21 15:19:27
         compiled from wystawione.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'config_load', 'wystawione.tpl', 1, false),array('modifier', 'nice_number', 'wystawione.tpl', 37, false),)), $this); ?>
<?php echo '';  echo smarty_function_config_load(array('file' => 'conf','section' => 'HEAD'), $this); echo ' ';  echo smarty_function_config_load(array('file' => 'conf','section' => 'PATH'), $this); echo '<linkrel="stylesheet" type="text/css" href="';  echo $this->_tpl_vars['style_dir'];  echo 'messages.css"><center><br><table><tr><td colspan="5" bgcolor="#362a1a" align="center" valign="baseline"><table cellspacing="0" cellpadding="0" border="0"><tr><td width="71px"><img border="0"src="';  echo $this->_tpl_vars['image_dir'];  echo 'table_decor_right_1.jpg"></td><td width="357px" align="center"><FONT color="#c8a27c"face="Lucida Calligraphy"><span style="valign: middle">Wystawione aukcje</span></font></b></td><td width="71px"><img border="0"src="';  echo $this->_tpl_vars['image_dir'];  echo 'table_decor_left_1.jpg"></td></tr></table></td></tr><tr><td class="header">CO:</td><td class="header">CENA:</td><td class="header">ILOSC:</td><td class="header">WARTO¦Æ:</td><td class="header">USUÑ:</td></tr>';  $_from = $this->_tpl_vars['spisTowaror']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['key'] => $this->_tpl_vars['item']):
 echo '';  if ($this->_tpl_vars['item']->podsumowanie):  echo '<!-- WYPISZ PODSUMOWANIE --><tr><td bgcolor="#000000">Razem ';  echo $this->_tpl_vars['item']->co;  echo '</td><td bgcolor="#000000"></td><td bgcolor="#000000" align="right">';  echo ((is_array($_tmp=$this->_tpl_vars['item']->ile)) ? $this->_run_mod_handler('nice_number', true, $_tmp) : smarty_modifier_nice_number($_tmp));  echo '</td><td bgcolor="#000000" align="right">';  echo ((is_array($_tmp=$this->_tpl_vars['item']->wartoscAukcji)) ? $this->_run_mod_handler('nice_number', true, $_tmp) : smarty_modifier_nice_number($_tmp));  echo '</td><td bgcolor="#000000"></td></tr><tr><td bgcolor="#000000"></td><td bgcolor="#000000"></td><td bgcolor="#000000"></td><td bgcolor="#000000"></td><td bgcolor="#000000"></td></tr>';  else:  echo '<!-- NIE PODSUMOWANIE --><tr><td bgcolor="#212223">';  echo $this->_tpl_vars['item']->co;  echo '</td><td bgcolor="#212223" align="right">';  echo ((is_array($_tmp=$this->_tpl_vars['item']->cena)) ? $this->_run_mod_handler('nice_number', true, $_tmp) : smarty_modifier_nice_number($_tmp));  echo '</td><td bgcolor="#212223" align="right">';  echo ((is_array($_tmp=$this->_tpl_vars['item']->ile)) ? $this->_run_mod_handler('nice_number', true, $_tmp) : smarty_modifier_nice_number($_tmp));  echo '</td><td bgcolor="#212223" align="right">';  echo ((is_array($_tmp=$this->_tpl_vars['item']->wartoscAukcji)) ? $this->_run_mod_handler('nice_number', true, $_tmp) : smarty_modifier_nice_number($_tmp));  echo '</td><td bgcolor="#212223" align="right"><a href=usun.php?id=';  echo $this->_tpl_vars['item']->id;  echo '>USUÑ</a></td></tr>';  endif;  echo ' ';  endforeach; endif; unset($_from);  echo '<tr bgcolor="#362a1a"><td colspan="5">&nbsp;</td></tr></table>';  $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "wystaw.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
  echo '</center></head></html>'; ?>
